# Generated by Django 2.2.15 on 2020-08-20 15:42

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ads',
            options={'verbose_name': 'Classified Ad', 'verbose_name_plural': 'Classified Ads'},
        ),
        migrations.AddField(
            model_name='ads',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ads',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='ads',
            name='specification',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
