# Generated by Django 2.2.15 on 2020-08-20 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_auto_20200820_2142'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ads',
            options={'verbose_name_plural': 'Classified Ads'},
        ),
    ]
