# Generated by Django 2.2.15 on 2020-08-22 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_auto_20200820_2159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ads',
            name='specification',
        ),
        migrations.AlterField(
            model_name='ads',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/%Y/%m/%d'),
        ),
    ]
