# Generated by Django 2.2.15 on 2020-08-22 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0004_auto_20200822_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
