# Generated by Django 2.2.15 on 2020-08-25 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0007_remove_ads_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='ads',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
