# Generated by Django 2.2.15 on 2020-08-25 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0009_auto_20200825_1722'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
