# Generated by Django 2.2.15 on 2020-09-18 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0015_auto_20200916_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='adsimages',
            name='image',
            field=models.ImageField(default=None, upload_to='uploads/%Y/%m/%d'),
        ),
    ]
