# Generated by Django 2.2.15 on 2020-09-18 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0016_auto_20200918_2004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ads',
            name='image',
        ),
    ]
