# Generated by Django 2.2.15 on 2020-09-22 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0017_remove_ads_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adsimages',
            options={'verbose_name_plural': 'Classified Ads Images'},
        ),
    ]
