# Generated by Django 2.2.15 on 2020-09-22 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0018_auto_20200922_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/category'),
        ),
    ]
