# Generated by Django 2.2.15 on 2020-09-23 16:53

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0021_author_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='ads',
            name='video',
            field=embed_video.fields.EmbedVideoField(blank=True, null=True),
        ),
    ]
