# Generated by Django 2.2.15 on 2020-09-24 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0023_auto_20200924_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='State',
        ),
    ]
